/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'eu-west-1',
    aws_cognito_identity_pool_id: 'eu-west-1:3aa92d70-bcc5-4fff-b7ea-ae3ab63b5125',
    aws_cognito_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_HjqCixhD6',
    aws_user_pools_web_client_id: '13aqvue1rfc160vrjbreg2aa6c',
    // aws_cognito_identity_pool_id: 'eu-west-1:f7b9b42e-798c-45d7-83fa-dbb3d3c9a8fa',
    // aws_cognito_region: 'eu-west-1',
    // aws_user_pools_web_client_id: '3g412j4m90mjlk16k18kpue5iv',
    // aws_user_pools_id: 'eu-west-1_xmc3h7vDY',
    oauth: {},
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
      passwordPolicyMinLength: 8,
      passwordPolicyCharacters: [],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
  };
  
  export default awsmobile;
  